###
POST http://localhost:8080/recordstore/records/register
Content-Type: application/json
Authorization: Basic RW1wbG95ZWU6VGhlQmVzdFBhc3N3b3Jk

{
    "artistName": "Ben de Testartiest",
    "title": "Ben de Musical",
    "genre": "Post Heavy Negative Wizard Metal",
    "label": "STERK records",
    "color": "pink",
    "year": 2005,
    "country": "Cocos Eilanden",
    "price": 20.50,
    "qtyInStock": 1
}

<> 2022-05-23T151227.200.json

###
GET http://localhost:8080/recordstore/records
Accept: application/json
Authorization: Basic Q3VzdG9tZXI6RXZlbkJldHRlclBhc3N3b3Jk

<> 2022-05-23T151227-1.200.json

###
GET http://localhost:8080/recordstore/records/artist/1
Accept: application/json
Authorization: Basic Q3VzdG9tZXI6RXZlbkJldHRlclBhc3N3b3Jk

<> 2022-05-23T151227-2.200.json

###
GET http://localhost:8080/recordstore/records/1
Accept: application/json
Authorization: Basic Q3VzdG9tZXI6RXZlbkJldHRlclBhc3N3b3Jk

<> 2022-05-23T151227-3.200.json

###
GET http://localhost:8080/recordstore/records/title/Ben de Musical
Accept: application/json
Authorization: Basic Q3VzdG9tZXI6RXZlbkJldHRlclBhc3N3b3Jk

<> 2022-05-23T151227-4.200.json

###
GET http://localhost:8080/recordstore/records/genre/Post Heavy Negative Wizard Metal
Accept: application/json
Authorization: Basic Q3VzdG9tZXI6RXZlbkJldHRlclBhc3N3b3Jk

<> 2022-05-23T151228.200.json

###
PUT http://localhost:8080/recordstore/records/2
Content-Type: application/json
Authorization: Basic RW1wbG95ZWU6VGhlQmVzdFBhc3N3b3Jk

{
  "artistName": "Ben de Testartiest",
  "title": "Ben de Musical",
  "genre": "Post Heavy Negative Wizard Metal",
  "label": "STERK records",
  "color": "pink",
  "year": 2005,
  "country": "Cocos Eilanden",
  "price": 30.50,
  "qtyInStock": 2
}

<> 2022-05-23T151228-1.200.json

###
DELETE http://localhost:8080/recordstore/records/1
Authorization: Basic YWRtaW46VmVyeUdvb2RQYXNzd29yZA==

<> 2022-05-23T151228.200.txt
